Add file expansion and file existance checks
lazear/sage pull request #134
Opened 2024-04-30 22:10 UTC by acesnik

https://github.com/lazear/sage/issues/133

2024-05-02 22:28 UTC, acesnik commented
I tested this out on a simple bash commandline.
* It works for pattern matching mzMLs, e.g. `*.mzML.` 
* When nothing matches, it returns `Error: `mzml_paths` must be set. For more information try '--help'`.
* With a malformed glob, e.g. `L[*.mzML`, it returns `Glob pattern error: Pattern syntax error near position 1: invalid range pattern`. This might create some undesirable behavior, treating every path as a glob request... What do you think?

2024-05-03 04:30 UTC, lazear requested changes
Instead of `eprintln!`, can you use `log::error!`? That will give us consistent output with the rest of the program, and enable filtering of logs

2024-05-04 16:59 UTC, acesnik commented
Yep, sounds good and made the change. :)

2024-05-08 15:45 UTC, lazear commented
After some quick testing, this appears to break s3 support if the url is specified via CLI - IMO the best way to do this will be to move this logic into the `sage-cloudpath` crate for now. This would also enable glob paths to work when specified via the JSON configuration file.

We could then implement a method on the `CloudPath` enum that handles globs for both S3 (via list-objects) and local files (via glob)

2026-05-08 21:34 UTC, closed without merging